### ISSUE TITLE
Null values passed to attributes

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.jdbc#15]
We don't seem to be handling null correctly.
The database may have empty values, and we are passing null values into the tuple attribute.  I got the following exception:
Exception in thread "Thread-14" java.lang.IllegalArgumentException: Null attribute value passed for index '4
	at com.ibm.streams.operator.internal.object.ObjectOutputTuple.nullAttribute(ObjectOutputTuple.java:232)
	at com.ibm.streams.operator.internal.object.ObjectOutputTuple.setString(ObjectOutputTuple.java:155)
	at com.ibm.streams.operator.internal.object.ObjectOutputTuple.setString(ObjectOutputTuple.java:196)
	at com.ibm.streamsx.jdbc.JDBCRun.submitOutputTuple(JDBCRun.java:596)
	at com.ibm.streamsx.jdbc.JDBCRun.processTuple(JDBCRun.java:462)
	at com.ibm.streamsx.jdbc.AbstractJDBCOperator.process(AbstractJDBCOperator.java:277)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.processTuple(OperatorAdapter.java:1465)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:803)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:796)
	at com.ibm.streams.operator.internal.network.DeserializingStream.tuple(DeserializingStream.java:76)
	at com.ibm.streams.operator.internal.network.DeserializingStream.processRawTuple(DeserializingStream.java:65)
	at com.ibm.streams.operator.internal.runtime.api.InputPortsConduit.processRawTuple(InputPortsConduit.java:100)
	at com.ibm.streams.operator.internal.jni.JNIBridge.process(JNIBridge.java:316)

**Comment by yiminy** [comment]
Fixed. If it is a null value from resultset, it will not pass into tuple attribute.

**Comment by yiminy** [comment]
I will add "null values" scenario into my test cases. Thanks...

**Comment by chanskw** [comment]
+1!  Thanks for the quick response.

I tried out the operator.  Worked great!
